<?php

namespace AppBundle\Repository;

use \AppBundle\Entity\User;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByUser(User $user, $deleted = false)
	{
		$qb = $this->getEntityManager()->createQueryBuilder()
			->select('l')
			->from('AppBundle:Location', 'l')
			->where('l.user = :user')
			->andWhere('l.deleted = :deleted')
			->setParameter('user', $user)
			->setParameter('deleted', $deleted);

		return $qb->getQuery()->getResult();
	}
}
