# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    app.image_uploader:
        class: AppBundle\Service\ImageUploader
        public: true

    app.location_creator:
        class: AppBundle\Service\LocationCreator
        arguments: ['@doctrine']
        public: true

    app.code_manager:
        class: AppBundle\Service\CodeManager
        arguments: ['@doctrine']
        public: true

    my.oauth_aware.user_provider.service:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
        arguments:
            - '@fos_user.user_manager'
            - ['pass properties as array']

    app.oauth.provider:
        class: UserBundle\Security\Core\User\FOSUBUserProvider
        arguments: ['@fos_user.user_manager', {facebook: facebookId}]